# Generated by Django 4.1.7 on 2023-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video1',
            field=models.URLField(blank=True, null=True),
        ),
    ]
