# Generated by Django 4.1.7 on 2023-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_video1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image7',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
