# Generated by Django 4.1.7 on 2023-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image7',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
