# Generated by Django 4.1.7 on 2023-03-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image7_alter_product_video1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
