# Generated by Django 4.1.7 on 2023-04-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_video2'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='short_intro',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
